spring:
  application:
    name: derecc.dev

  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/gestao_db}
    username: ${PGUSER:root}
    password: ${PGPASSWORD:root}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true

server:
  port: ${PORT:8080}
